Another way

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,54 +1,103 @@
-sudo: required
 language: android
-jdk: oraclejdk8
+jdk:
+  - oraclejdk8
 env:
   global:
-    - ADB_INSTALL_TIMEOUT=8
-    - ABI=x86_64
-    - EMU_FLAVOR=default
-  matrix:
-    #- API=18 ABI=armeabi-v7a
-    - API=24
-    #- API=25
+    - ANDROID_API=28
+    - EMULATOR_API=24
+    - ANDROID_BUILD_TOOLS=28.0.3
 android:
   components:
     - tools
+    - android-$EMULATOR_API
+    - platform-tools
+    - tools
     - build-tools-$ANDROID_BUILD_TOOLS
     - android-$ANDROID_API
+    - extra-android-support
+    - extra-android-m2repository
+    - extra-google-m2repository
+    - sys-img-armeabi-v7a-android-$EMULATOR_API
   licenses:
-    - android-sdk-preview-license-.+
-    - android-sdk-license-.+
-    - google-gdk-license-.+
-before_install:
-  - openssl aes-256-cbc
-    -K $encrypted_ffed81facfa0_key
-    -iv $encrypted_ffed81facfa0_iv
-    -in ./app/google-services.json.enc
-    -out ./app/google-services.json -d
+    - ".+"
+before_script:
+  - echo "y" | android update sdk -a --no-ui --filter android-$EMULATOR_API
+  - echo "y" | android update sdk -a --no-ui --filter sys-img-armeabi-v7a-android-$EMULATOR_API
+  - android list targets | grep -E '^id:' | awk -F '"' '{$1=""; print $2}' # list all targets
+  - echo no | android create avd --force -n test -t android-$EMULATOR_API --abi armeabi-v7a
+  - emulator -avd test -no-skin -no-window &
+  - android-wait-for-emulator
+  - adb shell input keyevent 82 &
+  - adb wait-for-device get-serialno
+  - cd ${TRAVIS_BUILD_DIR}
   - chmod +x gradlew
-  - yes | sdkmanager "platforms;android-28"
-  - yes | sdkmanager "build-tools;29.0.0"
-install:
-  - echo 'count=0' > /home/travis/.android/repositories.cfg # Avoid harmless sdkmanager warning
-    - echo y | sdkmanager "platform-tools" >/dev/null
-    - echo y | sdkmanager "tools" >/dev/null # A second time per Travis docs, gets latest versions
-    - echo y | sdkmanager "build-tools;28.0.3" >/dev/null # Implicit gradle dependency - gradle drives changes
-    - echo y | sdkmanager "platforms;android-$API" >/dev/null # We need the API of the emulator we will run
-    - echo y | sdkmanager "platforms;android-28" >/dev/null # We need the API of the current compileSdkVersion from gradle.properties
-    - echo y | sdkmanager --channel=4 "emulator" >/dev/null # Use canary channel to get emulator 29.x for x86_64 image support
-    - echo y | sdkmanager "extras;android;m2repository" >/dev/null
-    - echo y | sdkmanager "system-images;android-$API;$EMU_FLAVOR;$ABI" >/dev/null # install our emulator
-    - echo no | avdmanager create avd --force -n test -k "system-images;android-$API;$EMU_FLAVOR;$ABI" -c 10M
-    - emulator -verbose -avd test -no-accel -no-snapshot -no-window $AUDIO -camera-back none -camera-front none -selinux permissive -qemu -m 2048 &
-    - android-wait-for-emulator
-    - adb shell input keyevent 82 &
+  - ./gradlew --version
+  - ./gradlew clean
 script:
-  - ./gradlew build --stacktrace
-before_cache:
-  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
-  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
+  - |
+    ./gradlew build assembleAndroidTest -PtestCoverageEnabled='true'
+    retval=$?
+    if [ $retval -ne 0 ]; then
+      echo "error on assembling, exit code: "$retval
+      exit $retval
+    fi
+
+  # See http://stackoverflow.com/questions/21294945/error-unable-to-find-instrumentation-info-for-componentinfo
+  # Instead of this (which doesn't give any output during tests execution):
+  # - ./gradlew connectedCheck -PdisablePreDex --continue --stacktrace --debug
+  # run:
+  - |
+    ./gradlew :app:installDebug :app:installDebugAndroidTest -PtestCoverageEnabled='true'
+    retval=$?
+    if [ $retval -ne 0 ]; then
+      echo "error on install, exit code: "$retval
+      exit $retval
+    fi
+
+  #
+  # The below line causes Process crash due to absence of video device
+  #- adb shell am instrument -w -r -e debug false org.andstatus.app.tests/android.test.InstrumentationTestRunner
+  #
+  # Run only tests, marked with a special annotation:
+  # See https://developer.android.com/reference/android/test/InstrumentationTestRunner.html
+  # For testing one method only:
+  # - adb shell am instrument -w -r -e debug false -e coverage true -e class org.andstatus.app.service.CommandExecutorStrategyTest#testSearch org.andstatus.app.tests/androidx.test.runner.AndroidJUnitRunner
+  - |
+    adb shell am instrument -w -r -e executionMode travisTest -e coverage true org.andstatus.app.tests/androidx.test.runner.AndroidJUnitRunner |& tee build/adb-test.log
+    retval=$?
+    if [ $retval -ne 0 ]; then
+      echo "error in adb, exit code: "$retval
+      exit $retval
+    fi
+
+  # adb doesn't propagate exit code from tests, see https://code.google.com/p/android/issues/detail?id=3254
+  # So we need to parse saved terminal log
+  - |
+    cat build/adb-test.log | grep "INSTRUMENTATION_STATUS: stack=" | grep -v "org.junit.AssumptionViolatedException"
+    if [ $? -eq 0 ]; then
+      echo "Test failure found"
+      exit 1
+    else
+      cat build/adb-test.log | grep "OK ("
+    fi
+
+  # Copy coverage data from the emulator
+  - |
+    adb shell "rm /sdcard/Download/coverage.ec"
+    adb shell "run-as org.andstatus.app cp /data/user/0/org.andstatus.app/files/coverage.ec /sdcard/Download"
+  - cd app/build
+  # copy to "build" folder, where it will be found by Sonar scanner
+  - adb pull "/sdcard/Download/coverage.ec"
+  - cd ../..
+notifications:
+  email: false
 cache:
   directories:
-    - "$HOME/.gradle/caches/"
-    - "$HOME/.gradle/wrapper/"
-    - "$HOME/.android/build-cache"
+    - $HOME/.m2
+    - $HOME/.gradle/caches/
+    - $HOME/.gradle/wrapper/
+    - $HOME/.android/build-cache
+before_install:
+  - yes | sdkmanager "platforms;android-$ANDROID_API"
+after_success:
+  - ./gradlew sonarqube -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR_TOKEN -Dsonar.verbose=true
